## ImageRecognitionController.java

### Image 1
POST http://127.0.0.1:8080/image/openai4/recognition
Accept: text/plain

https://cdn.vox-cdn.com/thumbor/6WUQ-FozHdnzwKN7t31bJWPbdxI=/0x0:900x500/1400x1050/filters:focal(450x250:451x251)/cdn.vox-cdn.com/uploads/chorus_asset/file/6438793/this-is-fine.jpg

### Image 1
POST http://127.0.0.1:8080/image/ollama/recognition
Accept: text/plain

https://cdn.vox-cdn.com/thumbor/6WUQ-FozHdnzwKN7t31bJWPbdxI=/0x0:900x500/1400x1050/filters:focal(450x250:451x251)/cdn.vox-cdn.com/uploads/chorus_asset/file/6438793/this-is-fine.jpg

### Image 2
POST http://127.0.0.1:8080/image/openai4/recognition
Accept: text/plain

https://i.ibb.co/wSWg1v0/petah-whats-going-on-v0-64xmp31f7t5c1.png

### Image 2
POST http://127.0.0.1:8080/image/ollama/recognition
Accept: text/plain

https://i.ibb.co/wSWg1v0/petah-whats-going-on-v0-64xmp31f7t5c1.png

